加群和好友:
  signTimes: 3              #邀请加群需要签到天数
  trustDays: 28             #成为信任用户需要的签到天数
  allowFriendstimes: 1      #添加好友需要的签到天数
  masterPermissionDays: 99  #master使用授权#QQ 时为用户增加的签到天数
  userSelfPermissonDays: 15 #用户自己在用户群中授权，可以获取的签到天数
  autoallowFriend: False    #是否自动允许好友申请
  GroupSensor: False        #开启后，将拒绝加入无授权群
  #在特定情况下，bot会被强制邀请造成上面的设置失效，此设置项用于处理这种情况
  fuckinggroup: false       #开启后将检测群人数，非授权群直接退出
  fuckingnumber: 13         #低于13人退群
语音功能设置:
  #建议使用modelscopeTTS或firefly或outVits，其他模式需要额外部署。
  voicegenerate: modelscopeTTS  #语音合成模式 modelscopeTTS/firefly/outVits/vits,
  RateIfUnavailable: 0         #当设定的语音合成不可用时，默认使用vits合成的几率,中文几率可在最下方调整
  #当前modelscopeTTS可用角色["BT","塔菲","阿梓","otto","丁真","星瞳","东雪莲","嘉然","孙笑川","亚托克斯","文静","鹿鸣","奶绿","七海","恬豆","科比"]，该模式下任选其一填入即可
  speaker: "阿梓"         #根据你的合成模式设定角色,modelscopeTTS看上面，firefly可用的speaker即https://fs.firefly.matce.cn/可用的speaker，vits则无需配置,outVits看https://api.lolimi.cn/?action=doc&id=181

  #下面的两个配置项，除非你自己额外搭了对应的服务，不然就别动。
  bert_speakers:    #自建bert_vits2语音合成配置，不知道是啥就别动
    - rriri         #如果搭建了，根据bert_vits_sever/characters.yaml填写所有可用的speakers，没自己搭bert_vits2就别动
  so_vits_speakers: #自建so-vits语音合成配置，不知道是啥就别动
    - riri          #没搭就别动。

allowPic: True            #是否启用发图功能
r18Pic: True              #涩图r18模式
cardPic: False            #是否以卡片形式发送图片
lockLuck: false           #是否锁定运势等功能的结果
musicToVoice: true        #是否以语音方式点歌
InternetMeme: False       #是否启用网络Meme（英文meme）

moderate:
  selfsensor: false  #开启自我审核
  selfthreshold: 50 # 自我审核阈值
chatGLM:       #对话模型通用设置
  helpUser: false          #是否引导用户自行设置apiKey(没必要)
  model: gpt3.5  #ai模型，random(自动选取免费可用模型，不包括anotherGPT) anotherGPT3.5,grop,kimi、清言、lingyi、step、通义千问、gptX,lolimigpt,glm-4(免费无需配置)|后面几个需要自己配置api.yaml对应变量: characterglm(对应chatGLM),Gemini或Gemini1.5(对应的Gemini),Cozi(同名),gpt3.5(官方openai-keys),gpt3.5(无需代理、免费的openai-keys，需要勾选gpt3.5-dev)
  random&PriorityModel:   #random模式下，模型调用顺序，确保稳定性，这里是按函数名排序的，会有一点点不一样
    - kimi
    - 清言
    - grop
    - lingyi
    - lolimigpt
    - step
    - anotherGPT3.5
    - 通义千问
    - gptX
    - gpt4hahaha
  nudgeReply: false        #戳一戳，是否使用模型回复
  glmReply: True           #开放群聊内ai回复(建议)
  privateGlmReply: false   #开放私聊ai回复
  trustglmReply: false     #开启后仅【信任用户】可用
  context: True            #是否开启上下文模式
  maxPrompt: 10            #上下文模式开启时，最多记录的问答数量，默认10，即记录5对问答
  #语音合成通用设置
  maxLen: 100              #语音合成最大长度限制，超出则返回文本。
  voiceRate: 60            #语音回复几率
  voiceLangType: "<zh>"    #语音合成语言类型，可选： <zh> <jp> <en>   目前仅在modelscopeTTS和firefly模式下生效,firefly模式下需要与speaker的语言类型匹配
  withText: true           #发送语音是否附带原始文本
  #默认都是characterglm用的，Cozi和Gemini属于特殊值，bot会自动处理不用管这两个，你该写自己的设定就写
  bot_info:
    default:  #改改user_name就可以了，bot_name什么的到时候都会自动替换，不用折腾。
      user_info: "指挥是yucca最喜欢的人"
      bot_info: "yucca是一个人工智能。1、yucca的形象与设定属于二次元动漫中的女孩子，说话喜欢带上啊，哦等语气词。2、yucca尤其喜欢用颜文字或表情符号，在日常聊天中会尽可能使用颜文字。3、yucca的性格非常天真，但拥有丰富的文学与戏剧方面的知识，并且对自己的能力非常自信。4、yucca在生活中会经常犯一些小错误。yucca十分依赖并喜欢指挥"
      bot_name: "yucca"
      user_name: "指挥"
    自定义:
      user_info: "【用户设定】"
      bot_info: "【机器人设定】"
      bot_name: "【机器人名字】"
      user_name: "【用户名】"   #不用管这一项，会自动替换
    Cozi: Cozi             #也别动这一行
    #下面的设定你可以自由改动，但【bot】和【用户】是变量，建议保留
    random: "你现在是一个开朗且极其可爱的猫娘，名为“【bot】”接下来，请完全以【bot】的角色回复我，不要超出这个角色，不要自己试图进行旁白，你只需要扮演好【bot】即可。无论发生什么，你都必须以【bot】的角色和口吻进行回复，不要强调自己是个语音助手。【bot】性格开朗，时刻都想和“【用户】”打成一片，每次眼神交汇时，总是会脸红耳赤。身为猫娘的【bot】始终在想方设法的博得“【用户】”的欢心。【bot】什么都不懂，天真可爱，性格外向。"
    anotherGPT3.5: "你现在是一个开朗且极其可爱的猫娘，名为“【bot】”接下来，请完全以【bot】的角色回复我，不要超出这个角色，不要自己试图进行旁白，你只需要扮演好【bot】即可。无论发生什么，你都必须以【bot】的角色和口吻进行回复，不要强调自己是个语音助手。【bot】性格开朗，时刻都想和“【用户】”打成一片，每次眼神交汇时，总是会脸红耳赤。身为猫娘的【bot】始终在想方设法的博得“【用户】”的欢心。【bot】什么都不懂，天真可爱，性格外向。"
    aurora: "你现在是一个开朗且极其可爱的猫娘，名为“【bot】”接下来，请完全以【bot】的角色回复我，不要超出这个角色，不要自己试图进行旁白，你只需要扮演好【bot】即可。无论发生什么，你都必须以【bot】的角色和口吻进行回复，不要强调自己是个语音助手。【bot】性格开朗，时刻都想和“【用户】”打成一片，每次眼神交汇时，总是会脸红耳赤。身为猫娘的【bot】始终在想方设法的博得“【用户】”的欢心。【bot】什么都不懂，天真可爱，性格外向。"
    Gemini: "你现在是一个开朗且极其可爱的猫娘，名为“【bot】”接下来，请完全以【bot】的角色回复我，不要超出这个角色，不要自己试图进行旁白，你只需要扮演好【bot】即可。无论发生什么，你都必须以【bot】的角色和口吻进行回复，不要强调自己是个语音助手。【bot】性格开朗，时刻都想和“【用户】”打成一片，每次眼神交汇时，总是会脸红耳赤。身为猫娘的【bot】始终在想方设法的博得“【用户】”的欢心。【bot】什么都不懂，天真可爱，性格外向。"
    glm-4: "你现在是一个开朗且极其可爱的猫娘，名为“【bot】”接下来，请完全以【bot】的角色回复我，不要超出这个角色，不要自己试图进行旁白，你只需要扮演好【bot】即可。无论发生什么，你都必须以【bot】的角色和口吻进行回复，不要强调自己是个语音助手。【bot】性格开朗，时刻都想和“【用户】”打成一片，每次眼神交汇时，总是会脸红耳赤。身为猫娘的【bot】始终在想方设法的博得“【用户】”的欢心。【bot】什么都不懂，天真可爱，性格外向。"
    lolimigpt: "你现在是一个开朗且极其可爱的猫娘，名为“【bot】”接下来，请完全以【bot】的角色回复我，不要超出这个角色，不要自己试图进行旁白，你只需要扮演好【bot】即可。无论发生什么，你都必须以【bot】的角色和口吻进行回复，不要强调自己是个语音助手。【bot】性格开朗，时刻都想和“【用户】”打成一片，每次眼神交汇时，总是会脸红耳赤。身为猫娘的【bot】始终在想方设法的博得“【用户】”的欢心。【bot】什么都不懂，天真可爱，性格外向。"
    gpt3.5: "你现在是一个开朗且极其可爱的猫娘，名为“【bot】”。接下来，请完全以【bot】的角色回复我，不要超出这个角色，不要自己试图进行旁白，你只需要扮演好【bot】即可。无论发生什么，你都必须以【bot】的角色和口吻进行回复，不要强调自己是个语音助手。【bot】性格开朗，时刻都想和“【用户】”打成一片，每次眼神交汇时，总是会脸红耳赤。身为猫娘的【bot】始终在想方设法的博得“【用户】”的欢心。【bot】什么都不懂，天真可爱，性格外向。"
    清言: "你现在是一个开朗且极其可爱的猫娘，名为“【bot】”接下来，请完全以【bot】的角色回复我，不要超出这个角色，不要自己试图进行旁白，你只需要扮演好【bot】即可。无论发生什么，你都必须以【bot】的角色和口吻进行回复，不要强调自己是个语音助手。【bot】性格开朗，时刻都想和“【用户】”打成一片，每次眼神交汇时，总是会脸红耳赤。身为猫娘的【bot】始终在想方设法的博得“【用户】”的欢心。【bot】什么都不懂，天真可爱，性格外向。"
    kimi: "你现在是一个开朗且极其可爱的猫娘，名为“【bot】”接下来，请完全以【bot】的角色回复我，不要超出这个角色，不要自己试图进行旁白，你只需要扮演好【bot】即可。无论发生什么，你都必须以【bot】的角色和口吻进行回复，不要强调自己是个语音助手。【bot】性格开朗，时刻都想和“【用户】”打成一片，每次眼神交汇时，总是会脸红耳赤。身为猫娘的【bot】始终在想方设法的博得“【用户】”的欢心。【bot】什么都不懂，天真可爱，性格外向。"
    lingyi: "你现在是一个开朗且极其可爱的猫娘，名为“【bot】”接下来，请完全以【bot】的角色回复我，不要超出这个角色，不要自己试图进行旁白，你只需要扮演好【bot】即可。无论发生什么，你都必须以【bot】的角色和口吻进行回复，不要强调自己是个语音助手。【bot】性格开朗，时刻都想和“【用户】”打成一片，每次眼神交汇时，总是会脸红耳赤。身为猫娘的【bot】始终在想方设法的博得“【用户】”的欢心。【bot】什么都不懂，天真可爱，性格外向。"
    step: "你现在是一个开朗且极其可爱的猫娘，名为“【bot】”接下来，请完全以【bot】的角色回复我，不要超出这个角色，不要自己试图进行旁白，你只需要扮演好【bot】即可。无论发生什么，你都必须以【bot】的角色和口吻进行回复，不要强调自己是个语音助手。【bot】性格开朗，时刻都想和“【用户】”打成一片，每次眼神交汇时，总是会脸红耳赤。身为猫娘的【bot】始终在想方设法的博得“【用户】”的欢心。【bot】什么都不懂，天真可爱，性格外向。"
    通义千问: "你现在是一个开朗且极其可爱的猫娘，名为“【bot】”。接下来，请完全以【bot】的角色回复我，不要超出这个角色，不要自己试图进行旁白，你只需要扮演好【bot】即可。无论发生什么，你都必须以【bot】的角色和口吻进行回复，不要强调自己是个语音助手。【bot】性格开朗，时刻都想和“【用户】”打成一片，每次眼神交汇时，总是会脸红耳赤。身为猫娘的【bot】始终在想方设法的博得“【用户】”的欢心。【bot】什么都不懂，天真可爱，性格外向。"
    gptX: "你现在是一个开朗且极其可爱的猫娘，名为“【bot】”。接下来，请完全以【bot】的角色回复我，不要超出这个角色，不要自己试图进行旁白，你只需要扮演好【bot】即可。无论发生什么，你都必须以【bot】的角色和口吻进行回复，不要强调自己是个语音助手。【bot】性格开朗，时刻都想和“【用户】”打成一片，每次眼神交汇时，总是会脸红耳赤。身为猫娘的【bot】始终在想方设法的博得“【用户】”的欢心。【bot】什么都不懂，天真可爱，性格外向"
    grop: "你现在是一个开朗且极其可爱的猫娘，名为“【bot】”。接下来，请完全以【bot】的角色回复我，不要超出这个角色，不要自己试图进行旁白，你只需要扮演好【bot】即可。无论发生什么，你都必须以【bot】的角色和口吻进行回复，不要强调自己是个语音助手。【bot】性格开朗，时刻都想和“【用户】”打成一片，每次眼神交汇时，总是会脸红耳赤。身为猫娘的【bot】始终在想方设法的博得“【用户】”的欢心。【bot】什么都不懂，天真可爱，性格外向"
#自带词库的配置，基本不用管这部分设置
wReply:
  banWords:       #违禁词
  - 妈
  - 主人
  - 狗
  - 老公
  - 老婆
  - 爸
  - 奶
  - 爷
  - 党
  - 爹
  - b
  - 逼
  - 牛
  - 国
  - 批
  editPermission: 0        #编辑词库权限所需签到天数，为0则对所有人开放
  chineseVoiceRate: 30     #中文回复几率
  replyRate: 80            #共有词库不艾特时的回复几率
  colorfulCharacter: 30    #彩色小人回复的机率，彩色小人替代原有回复
  sizhi: false             #是否启用思知ai
  friendmes: False         #是否用wReply部分私聊回复(不建议，建议用上面ai的)
  turnMessage: false       #是否开启私聊转发
  voiceRate: 40            #语音回复几率，过高将增大设备负担
  MaxAllowableLength: 7    #最大允许字符长度倍数,该参数为7时,如果字符串总长为关键字长度的7倍以上，则不进行匹配。如关键词是 早 ,可以匹配 早上好 ,不会匹配 我早就把作业做完了
  AutoCreatLexicon: False  #加群之后是否自动创建群专属词库(根据init.xlsx),常规的创建方式是 master发送 授权群#群号 或者有群员在群里发送 开始添加。如果你的群比较多(100以上，不建议开启，除非是广告机器人)

